export const PeriodicTable = {
   H: {
      atomicNumber: "1",
      symbol: "H",
      name: "Hydrogen",
      atomicMass: "1.0080",
      standardState: "Gas",
      groupBlock: "Nonmetal",
   },
   He: {
      atomicNumber: "2",
      symbol: "He",
      name: "Helium",
      atomicMass: "4.00260",
      standardState: "Gas",
      groupBlock: "Noble Gas",
   },
   Li: {
      atomicNumber: "3",
      symbol: "Li",
      name: "Lithium",
      atomicMass: "7.0",
      standardState: "Solid",
      groupBlock: "Alkali Metal",
   },
   Be: {
      atomicNumber: "4",
      symbol: "Be",
      name: "Beryllium",
      atomicMass: "9.012183",
      standardState: "Solid",
      groupBlock: "Alkaline Earth Metal",
   },
   B: {
      atomicNumber: "5",
      symbol: "B",
      name: "Boron",
      atomicMass: "10.81",
      standardState: "Solid",
      groupBlock: "Metalloid",
   },
   C: {
      atomicNumber: "6",
      symbol: "C",
      name: "Carbon",
      atomicMass: "12.011",
      standardState: "Solid",
      groupBlock: "Nonmetal",
   },
   N: {
      atomicNumber: "7",
      symbol: "N",
      name: "Nitrogen",
      atomicMass: "14.007",
      standardState: "Gas",
      groupBlock: "Nonmetal",
   },
   O: {
      atomicNumber: "8",
      symbol: "O",
      name: "Oxygen",
      atomicMass: "15.999",
      standardState: "Gas",
      groupBlock: "Nonmetal",
   },
   F: {
      atomicNumber: "9",
      symbol: "F",
      name: "Fluorine",
      atomicMass: "18.99840316",
      standardState: "Gas",
      groupBlock: "Halogen",
   },
   Ne: {
      atomicNumber: "10",
      symbol: "Ne",
      name: "Neon",
      atomicMass: "20.180",
      standardState: "Gas",
      groupBlock: "Noble Gas",
   },
   Na: {
      atomicNumber: "11",
      symbol: "Na",
      name: "Sodium",
      atomicMass: "22.9897693",
      standardState: "Solid",
      groupBlock: "Alkali Metal",
   },
   Mg: {
      atomicNumber: "12",
      symbol: "Mg",
      name: "Magnesium",
      atomicMass: "24.305",
      standardState: "Solid",
      groupBlock: "Alkaline Earth Metal",
   },
   Al: {
      atomicNumber: "13",
      symbol: "Al",
      name: "Aluminum",
      atomicMass: "26.981538",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Si: {
      atomicNumber: "14",
      symbol: "Si",
      name: "Silicon",
      atomicMass: "28.085",
      standardState: "Solid",
      groupBlock: "Metalloid",
   },
   P: {
      atomicNumber: "15",
      symbol: "P",
      name: "Phosphorus",
      atomicMass: "30.97376200",
      standardState: "Solid",
      groupBlock: "Nonmetal",
   },
   S: {
      atomicNumber: "16",
      symbol: "S",
      name: "Sulfur",
      atomicMass: "32.07",
      standardState: "Solid",
      groupBlock: "Nonmetal",
   },
   Cl: {
      atomicNumber: "17",
      symbol: "Cl",
      name: "Chlorine",
      atomicMass: "35.45",
      standardState: "Gas",
      groupBlock: "Halogen",
   },
   Ar: {
      atomicNumber: "18",
      symbol: "Ar",
      name: "Argon",
      atomicMass: "39.9",
      standardState: "Gas",
      groupBlock: "Noble Gas",
   },
   K: {
      atomicNumber: "19",
      symbol: "K",
      name: "Potassium",
      atomicMass: "39.0983",
      standardState: "Solid",
      groupBlock: "Alkali Metal",
   },
   Ca: {
      atomicNumber: "20",
      symbol: "Ca",
      name: "Calcium",
      atomicMass: "40.08",
      standardState: "Solid",
      groupBlock: "Alkaline Earth Metal",
   },
   Sc: {
      atomicNumber: "21",
      symbol: "Sc",
      name: "Scandium",
      atomicMass: "44.95591",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Ti: {
      atomicNumber: "22",
      symbol: "Ti",
      name: "Titanium",
      atomicMass: "47.867",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   V: {
      atomicNumber: "23",
      symbol: "V",
      name: "Vanadium",
      atomicMass: "50.9415",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Cr: {
      atomicNumber: "24",
      symbol: "Cr",
      name: "Chromium",
      atomicMass: "51.996",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Mn: {
      atomicNumber: "25",
      symbol: "Mn",
      name: "Manganese",
      atomicMass: "54.93804",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Fe: {
      atomicNumber: "26",
      symbol: "Fe",
      name: "Iron",
      atomicMass: "55.84",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Co: {
      atomicNumber: "27",
      symbol: "Co",
      name: "Cobalt",
      atomicMass: "58.93319",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Ni: {
      atomicNumber: "28",
      symbol: "Ni",
      name: "Nickel",
      atomicMass: "58.693",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Cu: {
      atomicNumber: "29",
      symbol: "Cu",
      name: "Copper",
      atomicMass: "63.55",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Zn: {
      atomicNumber: "30",
      symbol: "Zn",
      name: "Zinc",
      atomicMass: "65.4",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Ga: {
      atomicNumber: "31",
      symbol: "Ga",
      name: "Gallium",
      atomicMass: "69.723",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Ge: {
      atomicNumber: "32",
      symbol: "Ge",
      name: "Germanium",
      atomicMass: "72.63",
      standardState: "Solid",
      groupBlock: "Metalloid",
   },
   As: {
      atomicNumber: "33",
      symbol: "As",
      name: "Arsenic",
      atomicMass: "74.92159",
      standardState: "Solid",
      groupBlock: "Metalloid",
   },
   Se: {
      atomicNumber: "34",
      symbol: "Se",
      name: "Selenium",
      atomicMass: "78.97",
      standardState: "Solid",
      groupBlock: "Nonmetal",
   },
   Br: {
      atomicNumber: "35",
      symbol: "Br",
      name: "Bromine",
      atomicMass: "79.90",
      standardState: "Liquid",
      groupBlock: "Halogen",
   },
   Kr: {
      atomicNumber: "36",
      symbol: "Kr",
      name: "Krypton",
      atomicMass: "83.80",
      standardState: "Gas",
      groupBlock: "Noble Gas",
   },
   Rb: {
      atomicNumber: "37",
      symbol: "Rb",
      name: "Rubidium",
      atomicMass: "85.468",
      standardState: "Solid",
      groupBlock: "Alkali Metal",
   },
   Sr: {
      atomicNumber: "38",
      symbol: "Sr",
      name: "Strontium",
      atomicMass: "87.62",
      standardState: "Solid",
      groupBlock: "Alkaline Earth Metal",
   },
   Y: {
      atomicNumber: "39",
      symbol: "Y",
      name: "Yttrium",
      atomicMass: "88.90584",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Zr: {
      atomicNumber: "40",
      symbol: "Zr",
      name: "Zirconium",
      atomicMass: "91.22",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Nb: {
      atomicNumber: "41",
      symbol: "Nb",
      name: "Niobium",
      atomicMass: "92.90637",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Mo: {
      atomicNumber: "42",
      symbol: "Mo",
      name: "Molybdenum",
      atomicMass: "95.95",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Tc: {
      atomicNumber: "43",
      symbol: "Tc",
      name: "Technetium",
      atomicMass: "96.90636",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Ru: {
      atomicNumber: "44",
      symbol: "Ru",
      name: "Ruthenium",
      atomicMass: "101.1",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Rh: {
      atomicNumber: "45",
      symbol: "Rh",
      name: "Rhodium",
      atomicMass: "102.9055",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Pd: {
      atomicNumber: "46",
      symbol: "Pd",
      name: "Palladium",
      atomicMass: "106.42",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Ag: {
      atomicNumber: "47",
      symbol: "Ag",
      name: "Silver",
      atomicMass: "107.868",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Cd: {
      atomicNumber: "48",
      symbol: "Cd",
      name: "Cadmium",
      atomicMass: "112.41",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   In: {
      atomicNumber: "49",
      symbol: "In",
      name: "Indium",
      atomicMass: "114.818",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Sn: {
      atomicNumber: "50",
      symbol: "Sn",
      name: "Tin",
      atomicMass: "118.71",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Sb: {
      atomicNumber: "51",
      symbol: "Sb",
      name: "Antimony",
      atomicMass: "121.760",
      standardState: "Solid",
      groupBlock: "Metalloid",
   },
   Te: {
      atomicNumber: "52",
      symbol: "Te",
      name: "Tellurium",
      atomicMass: "127.6",
      standardState: "Solid",
      groupBlock: "Metalloid",
   },
   I: {
      atomicNumber: "53",
      symbol: "I",
      name: "Iodine",
      atomicMass: "126.9045",
      standardState: "Solid",
      groupBlock: "Halogen",
   },
   Xe: {
      atomicNumber: "54",
      symbol: "Xe",
      name: "Xenon",
      atomicMass: "131.29",
      standardState: "Gas",
      groupBlock: "Noble Gas",
   },
   Cs: {
      atomicNumber: "55",
      symbol: "Cs",
      name: "Cesium",
      atomicMass: "132.9054520",
      standardState: "Solid",
      groupBlock: "Alkali Metal",
   },
   Ba: {
      atomicNumber: "56",
      symbol: "Ba",
      name: "Barium",
      atomicMass: "137.33",
      standardState: "Solid",
      groupBlock: "Alkaline Earth Metal",
   },
   La: {
      atomicNumber: "57",
      symbol: "La",
      name: "Lanthanum",
      atomicMass: "138.9055",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Ce: {
      atomicNumber: "58",
      symbol: "Ce",
      name: "Cerium",
      atomicMass: "140.116",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Pr: {
      atomicNumber: "59",
      symbol: "Pr",
      name: "Praseodymium",
      atomicMass: "140.90766",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Nd: {
      atomicNumber: "60",
      symbol: "Nd",
      name: "Neodymium",
      atomicMass: "144.24",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Pm: {
      atomicNumber: "61",
      symbol: "Pm",
      name: "Promethium",
      atomicMass: "144.91276",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Sm: {
      atomicNumber: "62",
      symbol: "Sm",
      name: "Samarium",
      atomicMass: "150.4",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Eu: {
      atomicNumber: "63",
      symbol: "Eu",
      name: "Europium",
      atomicMass: "151.964",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Gd: {
      atomicNumber: "64",
      symbol: "Gd",
      name: "Gadolinium",
      atomicMass: "157.25",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Tb: {
      atomicNumber: "65",
      symbol: "Tb",
      name: "Terbium",
      atomicMass: "158.92535",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Dy: {
      atomicNumber: "66",
      symbol: "Dy",
      name: "Dysprosium",
      atomicMass: "162.500",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Ho: {
      atomicNumber: "67",
      symbol: "Ho",
      name: "Holmium",
      atomicMass: "164.93033",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Er: {
      atomicNumber: "68",
      symbol: "Er",
      name: "Erbium",
      atomicMass: "167.26",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Tm: {
      atomicNumber: "69",
      symbol: "Tm",
      name: "Thulium",
      atomicMass: "168.93422",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Yb: {
      atomicNumber: "70",
      symbol: "Yb",
      name: "Ytterbium",
      atomicMass: "173.05",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Lu: {
      atomicNumber: "71",
      symbol: "Lu",
      name: "Lutetium",
      atomicMass: "174.9667",
      standardState: "Solid",
      groupBlock: "Lanthanide",
   },
   Hf: {
      atomicNumber: "72",
      symbol: "Hf",
      name: "Hafnium",
      atomicMass: "178.49",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Ta: {
      atomicNumber: "73",
      symbol: "Ta",
      name: "Tantalum",
      atomicMass: "180.9479",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   W: {
      atomicNumber: "74",
      symbol: "W",
      name: "Tungsten",
      atomicMass: "183.84",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Re: {
      atomicNumber: "75",
      symbol: "Re",
      name: "Rhenium",
      atomicMass: "186.207",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Os: {
      atomicNumber: "76",
      symbol: "Os",
      name: "Osmium",
      atomicMass: "190.2",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Ir: {
      atomicNumber: "77",
      symbol: "Ir",
      name: "Iridium",
      atomicMass: "192.22",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Pt: {
      atomicNumber: "78",
      symbol: "Pt",
      name: "Platinum",
      atomicMass: "195.08",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Au: {
      atomicNumber: "79",
      symbol: "Au",
      name: "Gold",
      atomicMass: "196.96657",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Hg: {
      atomicNumber: "80",
      symbol: "Hg",
      name: "Mercury",
      atomicMass: "200.59",
      standardState: "Liquid",
      groupBlock: "Transition Metal",
   },
   Tl: {
      atomicNumber: "81",
      symbol: "Tl",
      name: "Thallium",
      atomicMass: "204.383",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Pb: {
      atomicNumber: "82",
      symbol: "Pb",
      name: "Lead",
      atomicMass: "207",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Bi: {
      atomicNumber: "83",
      symbol: "Bi",
      name: "Bismuth",
      atomicMass: "208.98040",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Po: {
      atomicNumber: "84",
      symbol: "Po",
      name: "Polonium",
      atomicMass: "208.98243",
      standardState: "Solid",
      groupBlock: "Metalloid",
   },
   At: {
      atomicNumber: "85",
      symbol: "At",
      name: "Astatine",
      atomicMass: "209.98715",
      standardState: "Solid",
      groupBlock: "Halogen",
   },
   Rn: {
      atomicNumber: "86",
      symbol: "Rn",
      name: "Radon",
      atomicMass: "222.01758",
      standardState: "Gas",
      groupBlock: "Noble Gas",
   },
   Fr: {
      atomicNumber: "87",
      symbol: "Fr",
      name: "Francium",
      atomicMass: "223.01973",
      standardState: "Solid",
      groupBlock: "Alkali Metal",
   },
   Ra: {
      atomicNumber: "88",
      symbol: "Ra",
      name: "Radium",
      atomicMass: "226.02541",
      standardState: "Solid",
      groupBlock: "Alkaline Earth Metal",
   },
   Ac: {
      atomicNumber: "89",
      symbol: "Ac",
      name: "Actinium",
      atomicMass: "227.02775",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Th: {
      atomicNumber: "90",
      symbol: "Th",
      name: "Thorium",
      atomicMass: "232.038",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Pa: {
      atomicNumber: "91",
      symbol: "Pa",
      name: "Protactinium",
      atomicMass: "231.03588",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   U: {
      atomicNumber: "92",
      symbol: "U",
      name: "Uranium",
      atomicMass: "238.0289",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Np: {
      atomicNumber: "93",
      symbol: "Np",
      name: "Neptunium",
      atomicMass: "237.048172",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Pu: {
      atomicNumber: "94",
      symbol: "Pu",
      name: "Plutonium",
      atomicMass: "244.06420",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Am: {
      atomicNumber: "95",
      symbol: "Am",
      name: "Americium",
      atomicMass: "243.061380",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Cm: {
      atomicNumber: "96",
      symbol: "Cm",
      name: "Curium",
      atomicMass: "247.07035",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Bk: {
      atomicNumber: "97",
      symbol: "Bk",
      name: "Berkelium",
      atomicMass: "247.07031",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Cf: {
      atomicNumber: "98",
      symbol: "Cf",
      name: "Californium",
      atomicMass: "251.07959",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Es: {
      atomicNumber: "99",
      symbol: "Es",
      name: "Einsteinium",
      atomicMass: "252.0830",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Fm: {
      atomicNumber: "100",
      symbol: "Fm",
      name: "Fermium",
      atomicMass: "257.09511",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Md: {
      atomicNumber: "101",
      symbol: "Md",
      name: "Mendelevium",
      atomicMass: "258.09843",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   No: {
      atomicNumber: "102",
      symbol: "No",
      name: "Nobelium",
      atomicMass: "259.10100",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Lr: {
      atomicNumber: "103",
      symbol: "Lr",
      name: "Lawrencium",
      atomicMass: "266.120",
      standardState: "Solid",
      groupBlock: "Actinide",
   },
   Rf: {
      atomicNumber: "104",
      symbol: "Rf",
      name: "Rutherfordium",
      atomicMass: "267.122",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Db: {
      atomicNumber: "105",
      symbol: "Db",
      name: "Dubnium",
      atomicMass: "268.126",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Sg: {
      atomicNumber: "106",
      symbol: "Sg",
      name: "Seaborgium",
      atomicMass: "269.128",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Bh: {
      atomicNumber: "107",
      symbol: "Bh",
      name: "Bohrium",
      atomicMass: "270.133",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Hs: {
      atomicNumber: "108",
      symbol: "Hs",
      name: "Hassium",
      atomicMass: "269.1336",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Mt: {
      atomicNumber: "109",
      symbol: "Mt",
      name: "Meitnerium",
      atomicMass: "277.154",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Ds: {
      atomicNumber: "110",
      symbol: "Ds",
      name: "Darmstadtium",
      atomicMass: "282.166",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Rg: {
      atomicNumber: "111",
      symbol: "Rg",
      name: "Roentgenium",
      atomicMass: "282.169",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Cn: {
      atomicNumber: "112",
      symbol: "Cn",
      name: "Copernicium",
      atomicMass: "286.179",
      standardState: "Solid",
      groupBlock: "Transition Metal",
   },
   Nh: {
      atomicNumber: "113",
      symbol: "Nh",
      name: "Nihonium",
      atomicMass: "286.182",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Fl: {
      atomicNumber: "114",
      symbol: "Fl",
      name: "Flerovium",
      atomicMass: "290.192",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Mc: {
      atomicNumber: "115",
      symbol: "Mc",
      name: "Moscovium",
      atomicMass: "290.196",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Lv: {
      atomicNumber: "116",
      symbol: "Lv",
      name: "Livermorium",
      atomicMass: "293.205",
      standardState: "Solid",
      groupBlock: "Post-Transition Metal",
   },
   Ts: {
      atomicNumber: "117",
      symbol: "Ts",
      name: "Tennessine",
      atomicMass: "294.211",
      standardState: "Solid",
      groupBlock: "Halogen",
   },
   Og: {
      atomicNumber: "118",
      symbol: "Og",
      name: "Oganesson",
      atomicMass: "295.216",
      standardState: "Gas",
      groupBlock: "Noble Gas",
   },
} as const satisfies Record<string, IElementData>;

export interface IElementData {
   atomicNumber: string;
   symbol: string;
   name: string;
   atomicMass: string;
   standardState: StandardState;
   groupBlock: GroupBlock;
}

export const StandardStates = ["Solid", "Liquid", "Gas"] as const;
export type StandardState = (typeof StandardStates)[number];

export const GroupBlocks = [
   "Alkali Metal",
   "Alkaline Earth Metal",
   "Transition Metal",
   "Post-Transition Metal",
   "Metalloid",
   "Nonmetal",
   "Halogen",
   "Noble Gas",
   "Lanthanide",
   "Actinide",
] as const;

export type GroupBlock = (typeof GroupBlocks)[number];

export type ElementSymbol = keyof typeof PeriodicTable;
