import { range } from "../../utils/Helper";

export const PixelPerfect = true;
export const BattleTickInterval = 0.05;
export const ProductionTickInterval = 1;
export const ClientTickInterval = 5;
export const StatusEffectTickInterval = ProductionTickInterval;
export const GoldenRatio = (1 + Math.sqrt(5)) / 2;
export const QuantumToElement = 10;
export const BattleWinQuantum = 10;
export const BattleLossQuantum = 5;
export const DefaultElementChoices = 3;
export const BattleStartAmmoCycles = 5;
export const LaserArrayDamagePct = 1 / range(1, 10).reduce((a, b) => a + 1 / b, 0);
export const DamageToHPMultiplier = 10;
export const BalanceVersion = 1;
export const DefaultCooldown = 2;
export const CatalystPerCat = 3;
export const MaxBattleTick = 10 * 60;
export const MaxSuddenDeathTick = 5 * 60;
export const SuddenDeathUndamagedSec = 10;
export const MaxBuildingCount = 1000;
export const ElementThisRunColor = 0x94a9cd;
export const ElementPermanentColor = 0xffeaa7;
export const QualifierSpaceshipValuePercent = 0.9;
export const BaseWarmongerChangePerSec = 0.001;
export const FireBackDuration = 0.1;
export const FireForwardDuration = 0.4;
export const DiscordUrl = "https://discord.com/invite/Z3kFpawyts";
export const SteamUrl = "https://store.steampowered.com/app/3454630?utm_source=InGame";
export const TranslationUrl = "https://github.com/fishpondstudio/SpaceshipIdle/tree/main/packages/shared/src/languages";
export const PatchNotesUrl =
   "https://store.steampowered.com/news/app/3454630?utm_source=InGame&utm_campaign=PatchNotes";
export const SentryDSN = "https://54985c336c0b4c5495d31328bca6e101@bugreport.fishpondstudio.com/4";
export const Version = "0.5";
